// Generated by external policy engine
#ifndef OUTPUT_ENCLAVE_FUNCTIONS_H__
#define OUTPUT_ENCLAVE_FUNCTIONS_H__


#define RAW_VOTING_DATA_LENGTH 20
//voting table for data
typedef struct raw_voting_data {
    char id[RAW_VOTING_DATA_LENGTH];
    char name[RAW_VOTING_DATA_LENGTH];
    char sex[RAW_VOTING_DATA_LENGTH];
    char choice[RAW_VOTING_DATA_LENGTH];
    char rights[RAW_VOTING_DATA_LENGTH];
};

#ifdef __cplusplus
extern "C" {
#endif

// included in Enclave2_t.h: 
int general_output_function(int* integer_pointer, char* string_pointer, char function_identifier);
#ifdef __cplusplus
 }
#endif
#endif

